import{i as c,S as u}from"./assets/vendor-5b791d57.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const s={form:document.querySelector(".form"),input:document.querySelector(".input-search"),button:document.querySelector(".button"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader")};let a;s.loader.style.display="none";s.form.addEventListener("submit",f);function f(o){if(s.gallery.innerHTML="",s.loader.style.display="block",o.preventDefault(),s.input.value.trim()==="")return;const e=o.target.elements.search.value;p(e).then(n=>{n.hits.length===0?(d(),c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",transitionIn:"fadeInLeft"})):y(n.hits)}).catch(n=>{alert(n)}).finally(()=>{s.loader.style.display="none"}),o.target.reset()}function p(o){const e="42307458-71f98d2a331f0bd294b8fc1ec",n="https://pixabay.com",l="/api/",t=`?key=${e}&q=${o}&image_type=photo&orientation=horizontal&safesearch=true`,r=n+l+t;return fetch(r).then(i=>i.json())}function m(o){return o.map(e=>`
    <li class="gallery-item"><a href="${e.largeImageURL}">
          <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}"></a>
          <div class="info">
          <p> <span class="info-text">Likes</span> <br/> ${e.likes}</p>
          <p><span class="info-text">Views</span> <br/> ${e.views}</p>
          <p><span class="info-text">Comments</span> <br/> ${e.comments}</p>
          <p><span class="info-text">Downloads</span> <br/> ${e.downloads}</p>
          </div>
          </li>
    `).join("")}function y(o){const e=m(o);s.gallery.innerHTML=e,typeof a<"u"?a.refresh():a=new u(".gallery a",{captionsData:"alt",captionDelay:250})}function d(){s.gallery.innerHTML=""}
//# sourceMappingURL=commonHelpers.js.map
